### ISSUE TITLE
Dangling commas in bower.json

### ISSUE THREAD

**Issue by shaun-blake** [PolymerLabs/paper-styles#1]
I was attempting to do a bower install but it looks like the bower.json has some dangling commas and doesn't validate. They are in the "ignore" and "dependencies" sections.

**Comment by shaun-blake** [comment]
Maybe I should have just made a pull request.  Here it is: https://github.com/PolymerLabs/paper-styles/pull/2

**Comment by nevir** [comment]
Doh, sorry about that :(
