### ISSUE TITLE
bower ECMDERR - git://github.com/Polymer/font-roboto.git", exit code of #128

### ISSUE THREAD

**Issue by russomi** [PolymerLabs/paper-styles#3]
it appears that this dependency reference is incorrect?

```sh
$ bower install
bower not-cached    git://github.com/Polymer/font-roboto.git#*
bower resolve       git://github.com/Polymer/font-roboto.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/Polymer/font-roboto.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection refused
```

**Comment by nevir** [comment]
Hmm, [that repo does exist](https://github.com/Polymer/font-roboto). Are you behind a proxy or something that might block ssh?

**Comment by russomi** [comment]
Yes, that must be the issue... switching to "font-roboto": "https://github.com/Polymer/font-roboto" resolved the issue!

**Comment by nevir** [comment]
Aha!  You may want to have git rewrite any git:// URL to https:// for you

See
http://stackoverflow.com/questions/15669091/bower-install-using-only-https

**Comment by russomi** [comment]
Awesome.  Thanks for the tip!
